action_id: trunk-upgrade-available
date: 2023-11-13 05:03:54
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1699851834
full_timestamp:
  nanos: 153894000
  seconds: 1699851834
trunk_version: 1.17.1
